- hosts: spine,leaf
  become: yes
  roles:
    - interface_configuration
    - routing_configuration
      
- hosts: server
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - server_interface_configuration
