- hosts: spine,leaf,localhost
  remote_user: cumulus
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: Install NTP
      apt: name=ntp update_cache=yes

    - name: Write Timezone File
      lineinfile: dest=/etc/timezone line="Europe/Amsterdam"

    - name: Apply Timezone
      shell: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

    - name: Generate and Push NTP Config File
      template: src=./files/ntp.conf.j2 dest=/etc/ntp.conf

    - name: Restart NTP Service           
      service: name=ntp state=restarted

    - name: Stop and Disable NTP Service in the Default VRF
      service: name=ntp state=stopped enabled=false

    - name: Start and Enable NTP Service in the MGMT VRF
      service: name=ntp@mgmt state=started enabled=true
